## Notebook Stack

### Input Output
`pyarrow` is the defacto parquet and arrow standard library tooling in the python eco-system, offering exceptional performance, documentation and stability.

Its `fs` class allows connecting to parquet datasets in AWS S3, which is perfect for our use case.

### Computation
`polars` is fast replacing pandas as the primary python dataframe API. It is more tightly integrated with arrow (and pyarrow), has exceptional performance, greater than memory dataset manipulation, a more consistent and declarative API, built in plotting and many other advantages.

### Mapping
`pydeck` is a python binding for `deck.gl`, a GPU-powered framework for visual exploratory data analysis of large datasets. It is optimised for Jupyter notebooks and highly customisable.

Standard mapping tools like `folium` struggle to handle the number of mapped shapes, so we favor the more optimised `pydeck` library.

## Connecting to Cloud Optimised Datasets

NESP 5.9 datasets can be connected to via a pyarrow `S3FileSystem`.

The `S3FileSystem` manages the connection to the NESP 5.9 datasets stored in S3, resulting in a `pyarrow.Dataset` handle that we may use for efficient loading and subsetting of the dataset.

Note that a dataset can be comprised of a single parquet file or partitioned (into separate parquet fragments/files).

This step also makes the dataset schema available and file structure available allowing for pre-filtering without downloading the entire dataset.

In [1]:
import pyarrow
import pyarrow.fs
import pyarrow.dataset
import pyarrow.parquet

# Construct the anonymous file system responsible for reading from the public S3 bucket
FILE_SYSTEM = pyarrow.fs.S3FileSystem(
    region="ap-southeast-2", 
    anonymous=True,
)

DATASET_PATH = "aodn-cloud-optimised/diver_photoquadrat_qc_DwC.parquet"
SCHEMA_PATH = f"{DATASET_PATH}/_common_metadata"

# Create the dataset connection
# By convention, datasets are labelled `ds`
ds = pyarrow.dataset.dataset(
    source=DATASET_PATH,
    filesystem=FILE_SYSTEM,
    schema=pyarrow.parquet.read_schema(
        where=SCHEMA_PATH,
        filesystem=FILE_SYSTEM,
    ),
    partitioning="hive",
)

# The comprising files of the dataset can be inspected
print(f"There are `{len(list(ds.get_fragments()))}` cloud optimised file fragments.")

There are `19` cloud optimised file fragments.

In [2]:
ds.schema

class: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/class'
  type: 'string'
  nullable: 'True'
  long_name: 'Class'
  definition: 'The full scientific name of the class in which the dwc:Tax' + 17
genus: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/genus'
  type: 'string'
  nullable: 'True'
  long_name: 'Genus'
  definition: 'The full scientific name of the genus in which the dwc:Tax' + 17
order: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/order'
  type: 'string'
  nullable: 'True'
  long_name: 'Order'
  definition: 'The full scientific name of the order in which the dwc:Tax' + 17
family: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/family'
  type: 'string'
  nullable: 'True'
  long_name: 'Family'
  definition: 'The full scientific name of the family in which the dwc:Ta' + 18
phylum: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/phylum'
  type: 'string'
  nullable: 'True'
  long_name: 'Phylum'
  definition: 'The full scientific name of the phylum or division in whic' + 30
eventID: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/eventID'
  type: 'string'
  nullable: 'False'
  definition: 'An identifier for the set of information associated with a' + 132
h3Index: string
  -- field metadata --
  type: 'string'
  nullable: 'False'
  definition: 'A hexadecimal string representing a H3 polygon, derived fr' + 48
  resolution: '5'
kingdom: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/kingdom'
  type: 'string'
  nullable: 'True'
  long_name: 'Kingdom'
  definition: 'The full scientific name of the kingdom in which the dwc:T' + 19
eventDate: date32[day]
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/eventDate'
  type: 'date32[day]'
  nullable: 'False'
  long_name: 'Event Date'
  definition: 'The date-time or interval during which a dwc:Event occurre' + 123
taxonRank: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/taxonRank'
  type: 'string'
  nullable: 'True'
  long_name: 'Taxon Rank'
  definition: 'The taxonomic rank of the most specific name in the dwc:sc' + 13
RLSLineage: string
  -- field metadata --
  type: 'string'
  nullable: 'True'
  long_name: 'RLS Lineage'
  definition: 'The RLS lineage of the occurrence.'
occurrenceID: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/occurrenceID'
  type: 'string'
  nullable: 'False'
  long_name: 'Occurrence ID'
  definition: 'An identifier for the dwc:Occurrence (as opposed to a part' + 230
basisOfRecord: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/basisOfRecord'
  type: 'string'
  nullable: 'False'
  long_name: 'Basis Of Record'
  definition: 'The specific nature of the data record.'
catamiLineage: string
  -- field metadata --
  type: 'string'
  nullable: 'True'
  long_name: 'CATAMI Lineage'
  definition: 'The CATAMI lineage of the occurrence.'
scientificName: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/scientificName'
  type: 'string'
  nullable: 'True'
  long_name: 'Scientific Name'
  definition: 'The full scientific name, with authorship and date informa' + 136
associatedMedia: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/associatedOccurrences'
  type: 'string'
  nullable: 'True'
  long_name: 'Associated Media'
  definition: 'A list (concatenated and separated) of identifiers of othe' + 71
decimalLatitude: double
  -- field metadata --
  CRS: 'EPSG:4326'
  url: 'http://rs.tdwg.org/dwc/terms/decimalLatitude'
  type: 'double'
  nullable: 'False'
  long_name: 'Decimal Latitude'
  definition: 'The geographic latitude (in decimal degrees, using the spa' + 220
individualCount: int32
  -- field metadata --
  type: 'int32'
  nullable: 'True'
  long_name: 'Individual Count'
  definition: 'A number or enumeration value for the quantity of dwc:Orga' + 6
decimalLongitude: double
  -- field metadata --
  CRS: 'EPSG:4326'
  url: 'http://rs.tdwg.org/dwc/terms/decimalLongitude'
  type: 'double'
  nullable: 'False'
  long_name: 'Decimal Longitude'
  definition: 'The geographic longitude (in decimal degrees, using the sp' + 232
occurrenceStatus: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/occurrenceStatus'
  type: 'string'
  nullable: 'False'
  long_name: 'Occurrence Status'
  definition: 'A statement about the presence or absence of a dwc:Taxon a' + 21
scientificNameID: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/scientificNameID'
  type: 'string'
  nullable: 'True'
  long_name: 'Scientific Name ID'
  definition: 'An identifier for the nomenclatural (not taxonomic) detail' + 23
RLSIdentification: string
  -- field metadata --
  type: 'string'
  nullable: 'False'
  long_name: 'RLS Identification'
  definition: 'The RLS identification of the occurrence.'
catamiIdentification: string
  -- field metadata --
  type: 'string'
  nullable: 'False'
  long_name: 'CATAMI Identification'
  definition: 'The Catami identification of the occurrence.'
scientificNameAuthorship: string
  -- field metadata --
  url: 'http://rs.tdwg.org/dwc/terms/scientificNameAuthorship'
  type: 'string'
  nullable: 'True'
  long_name: 'Scientific Name Authorship'
  definition: 'The authorship information for the dwc:scientificName form' + 75
australianMarineRegionsTags: string
  -- field metadata --
  type: 'string'
  nullable: 'True'
  definition: 'A `|` separated tag column featuring common australian mar' + 11
polygon: string
  -- field metadata --
  type: 'string'
  units: '1'
  long_name: 'Spatial partition polygon'
filename: string
  -- field metadata --
  type: 'string'
  units: '1'
  long_name: 'Filename of the source file'
timestamp: int64
  -- field metadata --
  type: 'int64'
  units: '1'
  long_name: 'Partition timestamp'
-- schema metadata --
class: '{'url': 'http://rs.tdwg.org/dwc/terms/class', 'type': 'string', '' + 133
genus: '{'url': 'http://rs.tdwg.org/dwc/terms/genus', 'type': 'string', '' + 133
order: '{'url': 'http://rs.tdwg.org/dwc/terms/order', 'type': 'string', '' + 133
family: '{'url': 'http://rs.tdwg.org/dwc/terms/family', 'type': 'string',' + 137
phylum: '{'url': 'http://rs.tdwg.org/dwc/terms/phylum', 'type': 'string',' + 149
eventID: '{'url': 'http://rs.tdwg.org/dwc/terms/eventID', 'type': 'string' + 231
h3Index: '{'type': 'string', 'nullable': 'False', 'definition': 'A hexade' + 119
kingdom: '{'url': 'http://rs.tdwg.org/dwc/terms/kingdom', 'type': 'string' + 141
eventDate: '{'url': 'http://rs.tdwg.org/dwc/terms/eventDate', 'type': 'da' + 258
taxonRank: '{'url': 'http://rs.tdwg.org/dwc/terms/taxonRank', 'type': 'st' + 142
RLSLineage: '{'type': 'string', 'nullable': 'True', 'long_name': 'RLS Lin' + 58
occurrenceID: '{'url': 'http://rs.tdwg.org/dwc/terms/occurrenceID', 'type' + 369
basisOfRecord: '{'url': 'http://rs.tdwg.org/dwc/terms/basisOfRecord', 'ty' + 124
catamiLineage: '{'type': 'string', 'nullable': 'True', 'long_name': 'CATA' + 67
scientificName: '{'url': 'http://rs.tdwg.org/dwc/terms/scientificName', '' + 280
associatedMedia: '{'url': 'http://rs.tdwg.org/dwc/terms/associatedOccurre' + 224
decimalLatitude: '{'CRS': 'EPSG:4326', 'url': 'http://rs.tdwg.org/dwc/ter' + 388
individualCount: '{'type': 'int32', 'nullable': 'True', 'long_name': 'Ind' + 97
decimalLongitude: '{'CRS': 'EPSG:4326', 'url': 'http://rs.tdwg.org/dwc/te' + 403
occurrenceStatus: '{'url': 'http://rs.tdwg.org/dwc/terms/occurrenceStatus' + 172
scientificNameID: '{'url': 'http://rs.tdwg.org/dwc/terms/scientificNameID' + 174
RLSIdentification: '{'type': 'string', 'nullable': 'False', 'long_name': ' + 80
catamiIdentification: '{'type': 'string', 'nullable': 'False', 'long_name' + 89
scientificNameAuthorship: '{'url': 'http://rs.tdwg.org/dwc/terms/scientif' + 250
australianMarineRegionsTags: '{'type': 'string', 'nullable': 'True', 'def' + 82
polygon: '{'type': 'string', 'units': '1', 'long_name': 'Spatial partitio' + 11
filename: '{'type': 'string', 'units': '1', 'long_name': 'Filename of the' + 14
timestamp: '{'type': 'int64', 'units': '1', 'long_name': 'Partition times' + 6
global_attributes: '{'metadata_uuid': '0a65be6d-1c76-49ac-a151-80acf12361' + 49

In [3]:
import polars
import polars_h3

df = polars.DataFrame(
    data=ds.to_table(),
)
display(df)
display(df["eventID"].value_counts())

shape: (97_868, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ class     ┆ genus     ┆ order     ┆ family    ┆ … ┆ australia ┆ polygon   ┆ filename  ┆ timestam │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ nMarineRe ┆ ---       ┆ ---       ┆ p        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ gionsTags ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆           ┆           ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ IMCRA:Pro ┆ 010300000 ┆ nrmn.parq ┆ 11991456 │
│           ┆           ┆           ┆           ┆   ┆ vincial:N ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ame:Tasma ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ nia…      ┆ 000…      ┆           ┆          │
│ Ulvophyce ┆ Caulerpa  ┆ Bryopsida ┆ Caulerpac ┆ … ┆ IMCRA:Pro ┆ 010300000 ┆ nrmn.parq ┆ 11991456 │
│ ae        ┆           ┆ les       ┆ eae       ┆   ┆ vincial:N ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ame:Tasma ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ nia…      ┆ 000…      ┆           ┆          │
│ Florideop ┆ null      ┆ Corallina ┆ null      ┆ … ┆ IMCRA:Pro ┆ 010300000 ┆ nrmn.parq ┆ 11991456 │
│ hyceae    ┆           ┆ les       ┆           ┆   ┆ vincial:N ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ame:Tasma ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ nia…      ┆ 000…      ┆           ┆          │
│ Phaeophyc ┆ Ecklonia  ┆ Laminaria ┆ Lessoniac ┆ … ┆ IMCRA:Pro ┆ 010300000 ┆ nrmn.parq ┆ 11991456 │
│ eae       ┆           ┆ les       ┆ eae       ┆   ┆ vincial:N ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ame:Tasma ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ nia…      ┆ 000…      ┆           ┆          │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ IMCRA:Pro ┆ 010300000 ┆ nrmn.parq ┆ 11991456 │
│           ┆           ┆           ┆           ┆   ┆ vincial:N ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ame:Tasma ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ nia…      ┆ 000…      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ IMCRA:Mes ┆ 010300000 ┆ nrmn.parq ┆ 17672256 │
│           ┆           ┆           ┆           ┆   ┆ oscale:Wa ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ter       ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Type:Col… ┆ 000…      ┆           ┆          │
│ Phaeophyc ┆ Macrocyst ┆ Laminaria ┆ Laminaria ┆ … ┆ IMCRA:Mes ┆ 010300000 ┆ nrmn.parq ┆ 17672256 │
│ eae       ┆ is        ┆ les       ┆ ceae      ┆   ┆ oscale:Wa ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ter       ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Type:Col… ┆ 000…      ┆           ┆          │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ IMCRA:Mes ┆ 010300000 ┆ nrmn.parq ┆ 17672256 │
│           ┆           ┆           ┆           ┆   ┆ oscale:Wa ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ter       ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Type:Col… ┆ 000…      ┆           ┆          │
│ Phaeophyc ┆ Phyllospo ┆ Fucales   ┆ Seirococc ┆ … ┆ IMCRA:Mes ┆ 010300000 ┆ nrmn.parq ┆ 17672256 │
│ eae       ┆ ra        ┆           ┆ aceae     ┆   ┆ oscale:Wa ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ter       ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Type:Col… ┆ 000…      ┆           ┆          │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ IMCRA:Mes ┆ 010300000 ┆ nrmn.parq ┆ 17672256 │
│           ┆           ┆           ┆           ┆   ┆ oscale:Wa ┆ 001000000 ┆ uet       ┆ 00       │
│           ┆           ┆           ┆           ┆   ┆ ter       ┆ 050000000 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Type:Col… ┆ 000…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (8_567, 2)
┌───────────────────┬───────┐
│ eventID           ┆ count │
│ ---               ┆ ---   │
│ str               ┆ u32   │
╞═══════════════════╪═══════╡
│ 4000733_11_739    ┆ 12    │
│ 912354687_8_7900  ┆ 10    │
│ 912343342_6_0     ┆ 11    │
│ 912340188_8_3905  ┆ 10    │
│ 912350270_11_1696 ┆ 15    │
│ …                 ┆ …     │
│ 912352225_8_4015  ┆ 7     │
│ 912342284_11_975  ┆ 5     │
│ 912343826_6_0     ┆ 12    │
│ 912346174_7_0     ┆ 11    │
│ 2000951_3_0       ┆ 13    │
└───────────────────┴───────┘

In [4]:
import pydeck
import util

# Aggregate and generate h3 layers
h3_layers = util.generate_pydeck_hexagon_layers(
    df=(

        # H3 Aggregated dataframe with dataset and number of records attributes
        df
        .group_by(
            polars.col("h3Index"),
        )
        .agg(
            polars.col("eventID").count().alias("n_records"),
        )
    ),
    aggregate_column_name="n_records",
    n_quantiles = 10,
    color_palette="plasma",
)

# Run the map
deck = pydeck.Deck(
    layers=h3_layers,
    map_style=pydeck.map_styles.LIGHT_NO_LABELS,
    tooltip=util.TOOLTIP,
    initial_view_state=pydeck.ViewState(
        latitude=-30,
        longitude=135,
        zoom=2.5,
    ),
)
deck.show()

# Finding Trend Sites with H3
We may identify trend sites by finding a H3 cell associated with data over a time range.

For example, cell `84be639ffffffff` (situated over Port Phillip Bay) has over 5000 records.

We may aggregate the `individualCount` per `scientificName` and normalize by yearly total observations to generate a time series analysis.

In [5]:
import altair as alt

# Filter to Port Phillip Bay
_84be639ffffffff_df = (
    df
    .filter(
        polars.col("h3Index").eq("84be639ffffffff"),
    )
)

# Generate yearly aggregates
scientific_name_aggregated_84be639ffffffff_df = (
    _84be639ffffffff_df.group_by("scientificName", polars.col("eventDate").dt.year().alias("year"))
    .agg(
        polars.col("individualCount").sum().alias("species_count")
    )
    .with_columns(
        (polars.col("species_count") / polars.col("species_count").sum().over("year")).alias("year_proportion")
    )
    .sort("year_proportion", descending=True)
    .sort("year")
)

# Plot the year proportion of each `scientificName`
faceted_chart = (
    alt.Chart(scientific_name_aggregated_84be639ffffffff_df)
    .mark_line(point=True)
    .encode(
        x=alt.X("year:O", title="Year"),
        y=alt.Y("year_proportion:Q", title="Share", axis=alt.Axis(format="%")),
        color=alt.Color("scientificName:N", legend=None),
        tooltip=[
            alt.Tooltip("year:O", title="Year"),
            alt.Tooltip("species_count:Q", title="Count"),
            alt.Tooltip("year_proportion:Q", title="Share", format=".2%"),
        ],
    )
    .properties(width=220, height=150)
    .facet(
        facet=alt.Facet("scientificName:N", title="Scientific Name"),
        columns=3
    )
    .resolve_scale(y="independent")  # Change to 'shared' if you want a uniform Y-axis scale
)

faceted_chart.show()

alt.FacetChart(...)